// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwqjWuEw1vcuxOSMRf2GEkNWwt0h3Yq0U',
    appId: '1:482848523328:web:a2cc4a1a8b04949d0ecba5',
    messagingSenderId: '482848523328',
    projectId: 'room-sharing-4a199',
    authDomain: 'room-sharing-4a199.firebaseapp.com',
    storageBucket: 'room-sharing-4a199.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejKISyQJ6aXx3WQMoYU_uAB7sNqFdiMg',
    appId: '1:482848523328:android:2366fbc65b6cb0920ecba5',
    messagingSenderId: '482848523328',
    projectId: 'room-sharing-4a199',
    storageBucket: 'room-sharing-4a199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohaEYOxUPS6iC6EXumTjihanFHRa3d4g',
    appId: '1:482848523328:ios:3f27860848a71dad0ecba5',
    messagingSenderId: '482848523328',
    projectId: 'room-sharing-4a199',
    storageBucket: 'room-sharing-4a199.appspot.com',
    iosClientId: '482848523328-qf8gejhjmss3p61u7v06gvetk37k8fio.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohaEYOxUPS6iC6EXumTjihanFHRa3d4g',
    appId: '1:482848523328:ios:3f27860848a71dad0ecba5',
    messagingSenderId: '482848523328',
    projectId: 'room-sharing-4a199',
    storageBucket: 'room-sharing-4a199.appspot.com',
    iosClientId: '482848523328-qf8gejhjmss3p61u7v06gvetk37k8fio.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
